verdiDockWidgetDisplay -dock widgetDock_WelcomePage
verdiDockWidgetUndock -dock widgetDock_WelcomePage
verdiDockWidgetDock -dock widgetDock_WelcomePage
verdiDockWidgetHide -dock widgetDock_WelcomePage
debExit
